/*****************************************************************************
   data_api.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sat Sep 10 10:56:17 2022
 *****************************************************************************/

#ifndef DATA_API_H_
#define DATA_API_H_
#endif                                 /* DATA_API_H_ */
