/*****************************************************************************
   time.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu Sep  8 15:37:03 2022
 *****************************************************************************/

#ifndef TIME_H
#define TIME_H

uint32_T ticks(void);
uint32_T ticks_i(void);
uint32_T ticks_us(void);
uint32_T ticks_us_i(void);

#endif
