/*****************************************************************************
   Timer_BGND_G6Wyo.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu Sep  8 15:37:03 2022
 *****************************************************************************/

#include "Reha_Rap01.h"
#include "Reha_Rap01_private.h"

void Timer_BGND_G6Wyo(void)
{
  /* Timer_BGND_G6Wyo  ------   Background  */
  {
    {
      Reha_Rap01_Background();
    }
  }
}
