/*****************************************************************************
   can_general.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sat Sep 10 17:18:14 2022
 *****************************************************************************/

#include "core_env.h"
#include "sws_can.h"
#include "can_general.h"

/* CAN Message Info Table */
volatile can_msg_id_init_t canMsgInfo[] = {
  { 0x01, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_A },

  { 0x02, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_A },

  { 0x03, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_A },

  { 0x04, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_A },

  { 0x05, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_B },

  { 0x06, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_B },

  { 0x07, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_B },

  { 0x08, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_B },

  { 0x09, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_C },

  { 0x10, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_C },

  { 0x11, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_C },

  { 0x12, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_C },

  /* RX Messages - CAN1 Standard ID Rx Blocks */
  { 0x100, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x1FFFFFFF, CAN_BUS_A },

  { 0x200, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x1FFFFFFF, CAN_BUS_A },
};

volatile uint8 canMsgBuffInUse[] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
};

volatile can_msg_init_t can_init[1] = {
  { 14, (can_msg_id_init_t *)&canMsgInfo }
};
