/*****************************************************************************
   Timer_ooqlV.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sat Sep 10 17:18:14 2022
 *****************************************************************************/

#include "Reha_Rap01.h"
#include "Reha_Rap01_private.h"

void Timer_ooqlV(void)
{
  /* Timer_ooqlV  ------   Foreground  */
  {
    {
      Reha_Rap01_Foreground();
    }
  }
}
